# Generated by Django 5.0.1 on 2024-01-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "catgories",
            },
        ),
        migrations.CreateModel(
            name="JobCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("salary", models.CharField(max_length=50)),
                ("salary_period", models.CharField(max_length=25)),
                ("salary_calculation", models.CharField(max_length=25)),
                ("location", models.CharField(max_length=50)),
                (
                    "job_link",
                    models.CharField(default="", max_length=2083, unique=True),
                ),
                ("image_link", models.CharField(default="", max_length=2083)),
                ("image_width", models.SmallIntegerField()),
                ("image_height", models.SmallIntegerField()),
                ("offer_upload_date", models.CharField(max_length=50)),
                (
                    "source_link",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
            ],
        ),
    ]
