# Generated by Django 5.0.1 on 2024-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="job_link",
            field=models.CharField(default="", max_length=2083),
        ),
    ]
