# Generated by Django 5.0.1 on 2024-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_joboffer_job_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="bg_color",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobcity",
            name="locative_case_name",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
