# Generated by Django 5.0.1 on 2024-01-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_jobcategory_bg_color_jobcity_locative_case_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcategory",
            name="cvbankas_url",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
