# Generated by Django 5.0.1 on 2024-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_alter_joboffer_gross_pay_alter_joboffer_net_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joboffer",
            name="gross_pay",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="net_pay",
            field=models.CharField(default="", max_length=50),
        ),
    ]
