# Generated by Django 5.0.1 on 2024-01-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0007_alter_joboffer_gross_pay_alter_joboffer_net_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="gross_pay_from",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="gross_pay_to",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="net_pay_from",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="net_pay_to",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="pay_keyword",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="gross_pay",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="joboffer",
            name="net_pay",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
